# Generated by Django 5.0.3 on 2024-03-13 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapplication', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Application',
            new_name='Employee',
        ),
    ]
